package com.techelevator;

import junit.framework.TestCase;
import org.junit.Assert;
import org.junit.Test;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;

public class VendingMachineTest extends TestCase {

    // try catches? do they throw proper exceptions?

//    @Test
//    public boolean create_Inventory_exceptions(){
//        File testFile = new File("");
//        Scanner keyboard = new Scanner(System.in);
//        VendingMachine vm = new VendingMachine(keyboard);
//
//        try {
//            vm.createInventory();
//            fail( "My method didn't throw when I expected it to" );
//        } catch (IOException e) {
//            Assert.assert
//        }
//
//        Assert.assertNotNull(testFile);
//    }

// does it read file?

    // wrong number format test for feed money

//    @Test
//    public void does_extra_decimal_place_break_bigDecimal(){
//        double test = 2.555;
//        Scanner keyboard = new Scanner(System.in);
//        VendingMachine vm = new VendingMachine(keyboard);
//
//        Assert.assertEquals(null; vm.feedMoney(););
//
//
//    }

    // select product happy path
    // select product sold out and not enough money
    // update inventory
    // return change is getter


}